### ISSUE TITLE
Crystal 0.33.0 compatibility.

### ISSUE THREAD

**Issue by digitalextremist** [crystal-community/zeromq-crystal#18]
There was a breaking change in `0.33.0` of `Crystal`, at first glance revolving around `#each` being an undefined method on `Crystal::ThreadLocalValue(Crystal::Event)` in `#close` of `ZMQ::Socket`

**Comment by digitalextremist** [comment]
`each` became `each_and_clear` and then finally `consume_each`

* https://github.com/crystal-lang/crystal/commit/e6ace561c62a2a155cb26004e8d69573a99f0e16

**Comment by veelenga** [comment]
Thanks. Would you like to submit a PR to fix it?

**Comment by digitalextremist** [comment]
@veelenga almost there

**Comment by digitalextremist** [comment]
Resolved the above regarding `each` and continuing to list and resolve breaking changes:

* A call to `check_open` on `ZMQ::Socket` is added to `wait_writable` on `IO::Evented` which `ZMQ::Socket` does not have.

**Comment by RomainFranceschini** [comment]
Shouldn't this be closed since #19 got merged?
