### ISSUE TITLE
Does not compile with Cystal 1.0

### ISSUE THREAD

**Issue by kyku** [crystal-community/zeromq-crystal#26]
There is a problem using latest crystal:

> Unable to satisfy the following requirements:
> 
> - `crystal (< 1.0.0)` required by `zeromq 0.3.0+git.commit.d6d25ace3376aa0f36a6432ed88d35930d3640fb`
> Failed to resolve dependencies, try updating incompatible shards or use --ignore-crystal-version as a workaround if no update is available.
>

**Comment by bcardiff** [comment]
Fixed by #28
