### ISSUE TITLE
ZMQ::Socket(T) Generic do not make much sense 

### ISSUE THREAD

**Issue by k-solutions** [crystal-community/zeromq-crystal#4]
```
ctx = ZMQ::Context.new
sock = ZMQ::Socket(String).new ctx, ZMQ::REP
```

This would result in compile error for any send receive operation as String do not implement address

**Comment by benoist** [comment]
I had this in to allow a user to define a custom message struct.
So T has to be a message struct

**Comment by k-solutions** [comment]
I do understand and it make sense, but we may be better instead creating a abstract message and ensure the type is implementing abstract ?

**Comment by benoist** [comment]
Yes that's a better idea

**Comment by k-solutions** [comment]
Great ... I could create abstract class but would need a tip on how to enforce ZMQ::Socket to accept sub-classed types  on AbstractMessage

**Comment by benoist** [comment]
I think you can just replace T with AbstractMessage

**Comment by k-solutions** [comment]
Great would do that

**Comment by benoist** [comment]
As the generic is already removed and that seems fine for now. I will close this issue.
